name: gitleaks
on:
  pull_request:
    branches: 
      
  push:
    branches: 
      jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'  
    - name: gitleaks-action checkout(private)
      uses: actions/checkout@v2
      with:
        repository: tguff110/github-action
        ref: master 
        token: ${{ secrets.GIT_ACTION_TOKEN }} # stored in GitHub secrets
        path: ./gitleaksaction
    - name: run gitleaks action
      uses: ./gitleaksaction
